In [1]:
    import numpy as np
    import matplotlib.pyplot as plt
    from sklearn import neighbors, datasets, tree
    import graphviz

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

print("So lop: ", len(np.unique(iris_y)))
print("So du lieu thu: ", len(iris_y))


X0 = iris_X[iris_y == 0, :]
print("Mau don gian tu lop 0: \n", X0[:5, :])

X1 = iris_X[iris_y == 1, :]
print("Mau don gian tu lop 1: \n", X1[:5, :])

X2 = iris_X[iris_y == 2, :]
print("Mau don gian tu lop 2: \n", X2[:5, :])

So lop:  3
So du lieu thu:  150
Mau don gian tu lop 0: 
 [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
Mau don gian tu lop 1: 
 [[ 7.   3.2  4.7  1.4]
 [ 6.4  3.2  4.5  1.5]
 [ 6.9  3.1  4.9  1.5]
 [ 5.5  2.3  4.   1.3]
 [ 6.5  2.8  4.6  1.5]]
Mau don gian tu lop 2: 
 [[ 6.3  3.3  6.   2.5]
 [ 5.8  2.7  5.1  1.9]
 [ 7.1  3.   5.9  2.1]
 [ 6.3  2.9  5.6  1.8]
 [ 6.5  3.   5.8  2.2]]


In [4]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris_X, iris_y)

tree.export_graphviz(clf, out_file="tree.dot")
dot_data = tree.export_graphviz(clf, 
	out_file=None,
	feature_names=iris.feature_names,  
	class_names=iris.target_names,  
	filled=True, 
	rounded=True,  
	special_characters=True
	)